# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute Euclidean distances between a specified row and all other rows
#' Returns an unscaled positive numeric vector
#'
#'
#'
#' @param X A numeric matrix
#' @param x a row index
#' @export
dist_one <- function(X, x) {
    .Call('_albatross_dist_one', PACKAGE = 'albatross', X, x)
}

#' Compute Euclidean distances between all pairs of rows
#' Returns numeric matrix, scaled to [0,1]
#'
#'
#'
#' @param X A numeric matrix
#' @export
dist_all <- function(X) {
    .Call('_albatross_dist_all', PACKAGE = 'albatross', X)
}

